FROM nginx:alpine

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates
COPY nginx-cert/nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
COPY nginx-cert/nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key

# Expose ports
EXPOSE 80 443 8080

CMD ["nginx", "-g", "daemon off;"]

